kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: general
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
    numberOfReplicas: "1"  # This example uses a single replica, but you can adjust this value as needed
    dataLocality: "best-effort"
    staleReplicaTimeout: "2880"
    fromBackup: ""
    fsType: "ext4"
